### ISSUE TITLE
Fix react warning on System/Agents page

### ISSUE THREAD

**Issue by kroepke** [Graylog2/agent#8]
React prints:
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of AgentList. See http://fb.me/react-warning-keys for more information.

The table rows are probably missing the key attributes.

(Filing here to make it easier to keep track of agent related issues).

**Comment by dennisoelkers** [comment]
Fixed in Graylog2/graylog2-web-interface@aee14b672efa55e2537a81830cfd84d130e6fb35
